"大雨" = ":bucket:"
"大雪" = ":snow_capped_mountain:"
"暴風" = ":cyclone:"
"暴風雪" = ":cyclone:"
"風雪" = ":wind_blowing_face:"
"洪水" = ":ocean:"
"強風" = ":wind_blowing_face:"
"波浪" = ":ocean:"
"高潮" = ":ocean:"
"雷" = ":zap:"
"濃霧" = ":fog:"
"乾燥" = ":camel:"
"なだれ" = ":skier:"
"着氷" = ":ice_cube:"
"着雪" = ":skier:"
"融雪" = ":skier:"
"霜" = ":ice_cube:"
"低温" = ":cold_face:"