"大雨" = ":rotating_light:" # 通常の天候との差異が分かるようなemojiに
"大雪" = ":rotating_light:"
"暴風" = ":cyclone:"
"暴風雪" = ":cyclone:"
"風雪" = ":wind_blowing_face:"
"洪水" = ":ocean:"
"強風" = ":wind_blowing_face:"
"波浪" = ":ocean:"
"高潮" = ":ocean:"
"雷" = ":zap:"
"濃霧" = ":fog:"
"乾燥" = ":rotating_light:"
"なだれ" = ":rotating_light:"
"着氷" = ":rotating_light:"
"着雪" = ":rotating_light:"
"融雪" = ":rotating_light:"
"霜" = ":rotating_light:"
"低温" = ":cold_face:"