01 = ":sunny:"
02 = ":mostly_sunny:"
03 = ":umbrella:"
04 = ":snowflake:"
05 = ":mostly_sunny:"
06 = ":umbrella:"
07 = ":snowflake:"
08 = ":cloud:"
09 = ":partly_sunny:"
10 = ":umbrella:"
11 = ":snowflake:"
12 = ":partly_sunny:"
13 = ":umbrella:"
14 = ":snowflake:"
15 = ":umbrella:"
16 = ":umbrella:"
17 = ":umbrella:"
18 = ":umbrella:"
19 = ":umbrella:"
20 = ":umbrella:"
21 = ":umbrella:"
22 = ":umbrella_with_rain_drops:"
23 = ":snowflake:"
24 = ":snowflake:"
25 = ":snowflake:"
26 = ":snowflake:"
27 = ":snowflake:"
28 = ":snowflake:"
29 = ":snowflake:"
30 = ":snowman:"